/*
*------------------------------------------------------------------------
*AppGui.h
*
* This code was developed by Shunguang Wu in his spare time. No government
* or any client funds were used.
*
*
* THE SOFTWARE IS PROVIDED AS-IS AND WITHOUT WARRANTY OF ANY KIND,
* EXPRESS, IMPLIED OR OTHERWISE, INCLUDING WITHOUT LIMITATION, ANY
* WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
*
* IN NO EVENT SHALL THE AUTHOR OR DISTRIBUTOR BE LIABLE FOR
* ANY SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND,
* OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
* WHETHER OR NOT ADVISED OF THE POSSIBILITY OF DAMAGE, AND ON ANY THEORY OF
* LIABILITY, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
* OF THIS SOFTWARE.
*
* Permission to use, copy, modify, distribute, and sell this software and
* its documentation for any purpose is prohibited unless it is granted under
* the author's written notice.
*
* Copyright(c) 2020 by Shunguang Wu, All Right Reserved
*-------------------------------------------------------------------------
*/
/********************************************************************************
** This file is modified from the form generated by reading UI file 'mygui.ui'
**
**  Steps on How to modify this class
**
** (1) menu bar ->QT5->launch designer -> open clientgui.ui
** (2) use QT gui designed to edit the GUI
** (3) during building process, QT will re-write ui_clientgui.h 
**     (note ui_clientgui.h  is exclued by the project, and you need to put Q_OBJECT in RunGui.h)
** (4) copy and past the relative stuff from ui_clientgui.h to this AppGui.h
********************************************************************************/

#ifndef __APP_GUI_H__
#define __APP_GUI_H__

#include "libUtil/AppEnums.h"
#include "libCfg/Cfg.h"

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QFormLayout>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableView>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QCheckBox>

#include "ImgLabel.h"
#include "PlayerControls.h"

#include "GuiDefs.h"

inline void initMyResource() { Q_INIT_RESOURCE(appGuiRc); }

namespace xPlayer {
	enum AppGrpBox{
		//----------do not chg order beg -----	
		GRP_BOX_IMG = 0,
		GRP_BOX_LOGO,    //bottom left 
		GRP_BOX_CTRL,    //bottom right
		GRP_BOX_CUNT,
	};
	static std::vector<std::string> g_vGrpBoxName = {"imgWin", "logo", "ctrl" };

	enum AppPushButton {
		//----------do not chg order beg -----	
		PB_START_EXIT = 0,
		PB_IMG_FOLDER,    //bottom left 
		PB_MP3_FOLDER,    //bottom right
		PB_MAX_DISPLAY,
		PB_CUNT
	};
	static std::vector<std::string> g_vPushButtonName = { "Start", "Image Folder", "Mp3 Folder", "MaxDsp" };

	enum AppLineEdit {
		//----------do not chg order beg -----	
		LE_IMG_FOLDER = 0,
		LE_MP3_FOLDER, 
		LE_CUNT
	};
	static std::vector<std::string> g_vLineEditName = { "ImgFolderPath", "Mp3FolderPath"};

	//resource images
	enum AppResImg {
		RES_IMG_RED_BOX = 0,
		RES_IMG_GRN_BOX,
		RES_IMG_YEL_BOX,
		RES_IMG_GRY_BOX,
		RES_IMG_LOGO,
		RES_IMG_INIT,
		RES_IMG_DEFAULT,
		RES_IMG_CUNT
	};

	class AppGui : public QWidget
	{
	public:
		AppGui();
		void setupUi(QMainWindow *mainWin, CfgPtr &cfg);
		void showImg( const QPixmap &x );

		const QRect &getGuiRect();

		void resetGui();

		void setStartExitState(const char s) {
			m_startExitState = s;
			m_vPushButtons[PB_START_EXIT]->setText("Exit");
		}
		char getStartExitState() const {
			return m_startExitState;
		}

	private:
		void setupMenu();
		void setupGuiTexts();
		void initSettings();
		void setupGroupBoxs();
		void resizeGuiWin();
		void resizeLogoAndCtrlPanel();

	public:
		//main window and menu bar
		QMainWindow *m_mainWin;
		QWidget		*m_centralWidget;
		QMenuBar	*m_menuBar;
		QMenu		*m_menuFile;
		QMenu		*m_menuHelp;
		QAction		*m_actionExit;
		QAction		*m_actionHelp;
		QAction		*m_actionDecreaseSz;
		QAction		*m_actionAbout;
			
		//app widgets		
		QGroupBox	*m_vGrpBoxs[GRP_BOX_CUNT];
		//QLabel		*m_vLabelNames[GRP_BOX_CUNT];

		ImgLabel	*m_imgLabel;

		QLabel	    *m_labelLogo;
		QComboBox   *m_comboBoxPlaySpeed;
		QPushButton *m_vPushButtons[PB_CUNT];
		QLineEdit	*m_vLineEdits[LE_CUNT];
	private:
		CfgPtr			m_cfg;				//shared data pointer
		QRect			m_rectMainWin;
		char			m_startExitState;
		QRect			m_vRectGrpBox[GRP_BOX_CUNT];
		QPixmap         m_vQPixmap[RES_IMG_CUNT];
	};

} // namespace Ui

#endif
