#############################################################################
# Makefile for building: libqmake_dsp.a
# Generated by qmake (3.1) (Qt 5.9.2)
# Project:  qmake_dsp.pro
# Template: lib
# Command: /usr/local/Qt-5.9.2/bin/qmake qmake_dsp.pro
#############################################################################

MAKEFILE      = Makefile_dsp.mak

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_STATICPLUGIN -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -fPIC -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -fPIC -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/c++/7 -I/usr/local/Qt-5.9.2/include -I/usr/local/cuda/include -I/home/swu/projects/xEyes/src -I/home/swu/projects/xEyes/src/libDsp -I/usr/local/Qt-5.9.2/include/QtGui -I/usr/local/Qt-5.9.2/include/QtCore -I/home/swu/projects/build_xeyes/lib/libDsp -isystem /usr/include/libdrm -I/usr/local/Qt-5.9.2/mkspecs/linux-g++
QMAKE         = /usr/local/Qt-5.9.2/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/Qt-5.9.2/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/Qt-5.9.2/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qmake_dsp1.0.0
DISTDIR = /home/swu/projects/build_xeyes/lib/libDsp/qmake_dsp1.0.0
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = /home/swu/projects/build_xeyes/lib/libDsp/

####### Files

SOURCES       = /home/swu/projects/xEyes/src/libDsp/ThreadQt.cpp \
		/home/swu/projects/xEyes/src/libDsp/DspThread.cpp /home/swu/projects/build_xeyes/lib/libDsp/moc_ThreadQt.cpp \
		/home/swu/projects/build_xeyes/lib/libDsp/moc_DspThread.cpp
OBJECTS       = /home/swu/projects/build_xeyes/lib/libDsp/ThreadQt.o \
		/home/swu/projects/build_xeyes/lib/libDsp/DspThread.o \
		/home/swu/projects/build_xeyes/lib/libDsp/moc_ThreadQt.o \
		/home/swu/projects/build_xeyes/lib/libDsp/moc_DspThread.o
DIST          = /usr/local/Qt-5.9.2/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.9.2/mkspecs/common/unix.conf \
		/usr/local/Qt-5.9.2/mkspecs/common/linux.conf \
		/usr/local/Qt-5.9.2/mkspecs/common/sanitize.conf \
		/usr/local/Qt-5.9.2/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.9.2/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-5.9.2/mkspecs/common/g++-base.conf \
		/usr/local/Qt-5.9.2/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-5.9.2/mkspecs/qconfig.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.9.2/mkspecs/linux-g++/qmake.conf \
		/usr/local/Qt-5.9.2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Qt-5.9.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/toolchain.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/qt.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/resources.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/moc.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/qmake_use.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/file_copies.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/lex.prf \
		qmake_dsp.pro /home/swu/projects/xEyes/src/libDsp/ThreadQt.h \
		/home/swu/projects/xEyes/src/libDsp/DspThread.h /home/swu/projects/xEyes/src/libDsp/ThreadQt.cpp \
		/home/swu/projects/xEyes/src/libDsp/DspThread.cpp
QMAKE_TARGET  = qmake_dsp
DESTDIR       = /home/swu/projects/build_xeyes/lib/libs/
TARGET        = libqmake_dsp.a
TARGETD       = libqmake_dsp.a


first: all
####### Build rules

staticlib: /home/swu/projects/build_xeyes/lib/libs/$(TARGET)

/home/swu/projects/build_xeyes/lib/libs/$(TARGET):  $(OBJECTS) $(OBJCOMP) 
	@test -d /home/swu/projects/build_xeyes/lib/libs/ || mkdir -p /home/swu/projects/build_xeyes/lib/libs/
	-$(DEL_FILE) /home/swu/projects/build_xeyes/lib/libs/$(TARGET)
	$(AR) $(DESTDIR)$(TARGET) $(OBJECTS)


/home/swu/projects/xEyes/src/makefiles/Makefile_dsp.mak: qmake_dsp.pro /usr/local/Qt-5.9.2/mkspecs/linux-g++/qmake.conf /usr/local/Qt-5.9.2/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.9.2/mkspecs/common/unix.conf \
		/usr/local/Qt-5.9.2/mkspecs/common/linux.conf \
		/usr/local/Qt-5.9.2/mkspecs/common/sanitize.conf \
		/usr/local/Qt-5.9.2/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.9.2/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-5.9.2/mkspecs/common/g++-base.conf \
		/usr/local/Qt-5.9.2/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-5.9.2/mkspecs/qconfig.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt-5.9.2/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.9.2/mkspecs/linux-g++/qmake.conf \
		/usr/local/Qt-5.9.2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Qt-5.9.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/toolchain.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/qt.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/resources.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/moc.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/qmake_use.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/file_copies.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.9.2/mkspecs/features/lex.prf \
		qmake_dsp.pro \
		/usr/local/Qt-5.9.2/lib/libQt5Gui.prl \
		/usr/local/Qt-5.9.2/lib/libQt5Core.prl
	$(QMAKE) qmake_dsp.pro
/usr/local/Qt-5.9.2/mkspecs/features/spec_pre.prf:
/usr/local/Qt-5.9.2/mkspecs/common/unix.conf:
/usr/local/Qt-5.9.2/mkspecs/common/linux.conf:
/usr/local/Qt-5.9.2/mkspecs/common/sanitize.conf:
/usr/local/Qt-5.9.2/mkspecs/common/gcc-base.conf:
/usr/local/Qt-5.9.2/mkspecs/common/gcc-base-unix.conf:
/usr/local/Qt-5.9.2/mkspecs/common/g++-base.conf:
/usr/local/Qt-5.9.2/mkspecs/common/g++-unix.conf:
/usr/local/Qt-5.9.2/mkspecs/qconfig.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_core.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_help.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_location.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_network.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_script.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_x11extras.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Qt-5.9.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Qt-5.9.2/mkspecs/features/qt_functions.prf:
/usr/local/Qt-5.9.2/mkspecs/features/qt_config.prf:
/usr/local/Qt-5.9.2/mkspecs/linux-g++/qmake.conf:
/usr/local/Qt-5.9.2/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Qt-5.9.2/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt-5.9.2/mkspecs/features/toolchain.prf:
/usr/local/Qt-5.9.2/mkspecs/features/default_pre.prf:
/usr/local/Qt-5.9.2/mkspecs/features/resolve_config.prf:
/usr/local/Qt-5.9.2/mkspecs/features/default_post.prf:
/usr/local/Qt-5.9.2/mkspecs/features/warn_on.prf:
/usr/local/Qt-5.9.2/mkspecs/features/qt.prf:
/usr/local/Qt-5.9.2/mkspecs/features/resources.prf:
/usr/local/Qt-5.9.2/mkspecs/features/moc.prf:
/usr/local/Qt-5.9.2/mkspecs/features/unix/opengl.prf:
/usr/local/Qt-5.9.2/mkspecs/features/unix/thread.prf:
/usr/local/Qt-5.9.2/mkspecs/features/qmake_use.prf:
/usr/local/Qt-5.9.2/mkspecs/features/file_copies.prf:
/usr/local/Qt-5.9.2/mkspecs/features/testcase_targets.prf:
/usr/local/Qt-5.9.2/mkspecs/features/exceptions.prf:
/usr/local/Qt-5.9.2/mkspecs/features/yacc.prf:
/usr/local/Qt-5.9.2/mkspecs/features/lex.prf:
qmake_dsp.pro:
/usr/local/Qt-5.9.2/lib/libQt5Gui.prl:
/usr/local/Qt-5.9.2/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) qmake_dsp.pro

qmake_all: FORCE


all: /home/swu/projects/xEyes/src/makefiles/Makefile_dsp.mak /home/swu/projects/build_xeyes/lib/libs/$(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Qt-5.9.2/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents /home/swu/projects/xEyes/src/libDsp/ThreadQt.h /home/swu/projects/xEyes/src/libDsp/DspThread.h $(DISTDIR)/
	$(COPY_FILE) --parents /home/swu/projects/xEyes/src/libDsp/ThreadQt.cpp /home/swu/projects/xEyes/src/libDsp/DspThread.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) /home/swu/projects/build_xeyes/lib/libs/$(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) /home/swu/projects/xEyes/src/makefiles/Makefile_dsp.mak


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: /home/swu/projects/build_xeyes/lib/libDsp/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) /home/swu/projects/build_xeyes/lib/libDsp/moc_predefs.h
/home/swu/projects/build_xeyes/lib/libDsp/moc_predefs.h: /usr/local/Qt-5.9.2/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -fPIC -std=gnu++11 -Wall -W -dM -E -o /home/swu/projects/build_xeyes/lib/libDsp/moc_predefs.h /usr/local/Qt-5.9.2/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: /home/swu/projects/build_xeyes/lib/libDsp/moc_ThreadQt.cpp /home/swu/projects/build_xeyes/lib/libDsp/moc_DspThread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) /home/swu/projects/build_xeyes/lib/libDsp/moc_ThreadQt.cpp /home/swu/projects/build_xeyes/lib/libDsp/moc_DspThread.cpp
/home/swu/projects/build_xeyes/lib/libDsp/moc_ThreadQt.cpp: /usr/local/Qt-5.9.2/include/QtCore/qthread.h \
		/usr/local/Qt-5.9.2/include/QtCore/qobject.h \
		/usr/local/Qt-5.9.2/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.9.2/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.9.2/include/QtCore/qglobal.h \
		/usr/local/Qt-5.9.2/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/Qt-5.9.2/include/QtCore/qconfig.h \
		/usr/local/Qt-5.9.2/include/QtCore/qtcore-config.h \
		/usr/local/Qt-5.9.2/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.9.2/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.9.2/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.9.2/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.9.2/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.9.2/include/QtCore/qlogging.h \
		/usr/local/Qt-5.9.2/include/QtCore/qflags.h \
		/usr/local/Qt-5.9.2/include/QtCore/qatomic.h \
		/usr/local/Qt-5.9.2/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.9.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.9.2/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.9.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.9.2/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.9.2/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.9.2/include/QtCore/qmutex.h \
		/usr/local/Qt-5.9.2/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.9.2/include/QtCore/qversiontagging.h \
		/usr/local/Qt-5.9.2/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.9.2/include/QtCore/qstring.h \
		/usr/local/Qt-5.9.2/include/QtCore/qchar.h \
		/usr/local/Qt-5.9.2/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.9.2/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.9.2/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.9.2/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.9.2/include/QtCore/qlist.h \
		/usr/local/Qt-5.9.2/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.9.2/include/QtCore/qiterator.h \
		/usr/local/Qt-5.9.2/include/QtCore/qhashfunctions.h \
		/usr/local/Qt-5.9.2/include/QtCore/qpair.h \
		/usr/local/Qt-5.9.2/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.9.2/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.9.2/include/QtCore/qregexp.h \
		/usr/local/Qt-5.9.2/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.9.2/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.9.2/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.9.2/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.9.2/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.9.2/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.9.2/include/QtCore/qobject_impl.h \
		/home/swu/projects/xEyes/src/libUtil/util.h \
		/home/swu/projects/xEyes/src/libUtil/DataTypes.h \
		/home/swu/projects/xEyes/src/libUtil/AppEnums.h \
		/home/swu/projects/xEyes/src/libUtil/AppLog.h \
		/home/swu/projects/xEyes/src/libUtil/UtilDefs.h \
		/home/swu/projects/xEyes/src/libUtil/FileUtil.h \
		/home/swu/projects/xEyes/src/libUtil/UtilFuncs.h \
		/home/swu/projects/xEyes/src/libUtil/Roi.h \
		/home/swu/projects/xEyes/src/libUtil/CvUtilFuncs.h \
		/home/swu/projects/xEyes/src/libCfg/Cfg.h \
		/home/swu/projects/xEyes/src/libCfg/CfgLog.h \
		/home/swu/projects/xEyes/src/libCfg/CfgBase.h \
		/home/swu/projects/xEyes/src/libCfg/CfgDefs.h \
		/home/swu/projects/xEyes/src/libCfg/CfgCam.h \
		/home/swu/projects/xEyes/src/libCfg/CfgLocalView.h \
		/home/swu/projects/xEyes/src/libDc/DcUI.h \
		/home/swu/projects/xEyes/src/libDc/Dc.h \
		/home/swu/projects/xEyes/src/libDc/YuvCircularQ_h.h \
		/home/swu/projects/xEyes/src/libDc/YuvFrm_h.h \
		/home/swu/projects/xEyes/src/libDc/DsDefs.h \
		/home/swu/projects/xEyes/src/libDc/YuvFrm_d.h \
		/usr/local/cuda/include/cuda_runtime.h \
		/usr/local/cuda/include/crt/host_config.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/crt/host_defines.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/library_types.h \
		/usr/local/cuda/include/channel_descriptor.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/driver_functions.h \
		/usr/local/cuda/include/vector_functions.h \
		/usr/local/cuda/include/vector_functions.hpp \
		/usr/local/cuda/include/crt/device_functions.h \
		/usr/local/cuda/include/crt/device_functions.hpp \
		/usr/local/cuda/include/device_atomic_functions.h \
		/usr/local/cuda/include/device_atomic_functions.hpp \
		/usr/local/cuda/include/crt/device_double_functions.h \
		/usr/local/cuda/include/crt/device_double_functions.hpp \
		/usr/local/cuda/include/sm_20_atomic_functions.h \
		/usr/local/cuda/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda/include/sm_32_atomic_functions.h \
		/usr/local/cuda/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda/include/sm_35_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.hpp \
		/usr/local/cuda/include/sm_20_intrinsics.h \
		/usr/local/cuda/include/sm_20_intrinsics.hpp \
		/usr/local/cuda/include/sm_30_intrinsics.h \
		/usr/local/cuda/include/sm_30_intrinsics.hpp \
		/usr/local/cuda/include/sm_32_intrinsics.h \
		/usr/local/cuda/include/sm_32_intrinsics.hpp \
		/usr/local/cuda/include/sm_35_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.hpp \
		/usr/local/cuda/include/crt/sm_70_rt.h \
		/usr/local/cuda/include/crt/sm_70_rt.hpp \
		/usr/local/cuda/include/surface_functions.h \
		/usr/local/cuda/include/cuda_surface_types.h \
		/usr/local/cuda/include/texture_fetch_functions.h \
		/usr/local/cuda/include/cuda_texture_types.h \
		/usr/local/cuda/include/texture_indirect_functions.h \
		/usr/local/cuda/include/surface_indirect_functions.h \
		/usr/local/cuda/include/crt/common_functions.h \
		/usr/local/cuda/include/crt/math_functions.h \
		/usr/local/cuda/include/crt/func_macro.h \
		/usr/local/cuda/include/crt/math_functions.hpp \
		/usr/local/cuda/include/math_constants.h \
		/usr/local/cuda/include/device_launch_parameters.h \
		/usr/local/cuda/include/npp.h \
		/usr/local/cuda/include/nppversion.h \
		/usr/local/cuda/include/nppdefs.h \
		/usr/local/cuda/include/nppcore.h \
		/usr/local/cuda/include/nppi.h \
		/usr/local/cuda/include/nppi_support_functions.h \
		/usr/local/cuda/include/nppi_data_exchange_and_initialization.h \
		/usr/local/cuda/include/nppi_arithmetic_and_logical_operations.h \
		/usr/local/cuda/include/nppi_color_conversion.h \
		/usr/local/cuda/include/nppi_threshold_and_compare_operations.h \
		/usr/local/cuda/include/nppi_morphological_operations.h \
		/usr/local/cuda/include/nppi_filtering_functions.h \
		/usr/local/cuda/include/nppi_statistics_functions.h \
		/usr/local/cuda/include/nppi_linear_transforms.h \
		/usr/local/cuda/include/nppi_geometry_transforms.h \
		/usr/local/cuda/include/nppi_compression_functions.h \
		/usr/local/cuda/include/nppi_computer_vision.h \
		/usr/local/cuda/include/npps.h \
		/usr/local/cuda/include/npps_support_functions.h \
		/usr/local/cuda/include/npps_initialization.h \
		/usr/local/cuda/include/npps_conversion_functions.h \
		/usr/local/cuda/include/npps_arithmetic_and_logical_operations.h \
		/usr/local/cuda/include/npps_statistics_functions.h \
		/usr/local/cuda/include/npps_filtering_functions.h \
		/home/swu/projects/xEyes/src/libDc/RgbFrm_d.h \
		/home/swu/projects/xEyes/src/libDc/RgbCircularQ_h.h \
		/home/swu/projects/xEyes/src/libDc/RgbFrm_h.h \
		/home/swu/projects/xEyes/src/libDc/FrmInfoCircularQ.h \
		/home/swu/projects/xEyes/src/libDc/FrmInfo.h \
		/home/swu/projects/xEyes/src/libDc/DetFrm_h.h \
		/home/swu/projects/xEyes/src/libDc/DspFrm_h.h \
		/usr/local/Qt-5.9.2/include/QtGui/QPixmap \
		/usr/local/Qt-5.9.2/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.9.2/include/QtGui/qtguiglobal.h \
		/usr/local/Qt-5.9.2/include/QtGui/qtgui-config.h \
		/usr/local/Qt-5.9.2/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.9.2/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.9.2/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.9.2/include/QtCore/qrect.h \
		/usr/local/Qt-5.9.2/include/QtCore/qmargins.h \
		/usr/local/Qt-5.9.2/include/QtCore/qsize.h \
		/usr/local/Qt-5.9.2/include/QtCore/qpoint.h \
		/usr/local/Qt-5.9.2/include/QtGui/qcolor.h \
		/usr/local/Qt-5.9.2/include/QtGui/qrgb.h \
		/usr/local/Qt-5.9.2/include/QtGui/qrgba64.h \
		/usr/local/Qt-5.9.2/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.9.2/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.9.2/include/QtCore/qhash.h \
		/usr/local/Qt-5.9.2/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.9.2/include/QtGui/qimage.h \
		/usr/local/Qt-5.9.2/include/QtGui/qpixelformat.h \
		/usr/local/Qt-5.9.2/include/QtGui/qtransform.h \
		/usr/local/Qt-5.9.2/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.9.2/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.9.2/include/QtCore/qvector.h \
		/usr/local/Qt-5.9.2/include/QtGui/qregion.h \
		/usr/local/Qt-5.9.2/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.9.2/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.9.2/include/QtCore/qline.h \
		/usr/local/Qt-5.9.2/include/QtGui/qpainterpath.h \
		/home/swu/projects/xEyes/src/libDsp/DspDefs.h \
		/home/swu/projects/xEyes/src/libDsp/ThreadQt.h \
		/home/swu/projects/build_xeyes/lib/libDsp/moc_predefs.h \
		/usr/local/Qt-5.9.2/bin/moc
	/usr/local/Qt-5.9.2/bin/moc $(DEFINES) --include /home/swu/projects/build_xeyes/lib/libDsp/moc_predefs.h -I/usr/local/Qt-5.9.2/mkspecs/linux-g++ -I/media/swu/ssd512/projects/xEyes/src/makefiles -I/usr/include/c++/7 -I/usr/local/Qt-5.9.2/include -I/usr/local/cuda/include -I/home/swu/projects/xEyes/src -I/home/swu/projects/xEyes/src/libDsp -I/usr/local/Qt-5.9.2/include/QtGui -I/usr/local/Qt-5.9.2/include/QtCore -I/usr/include/c++/7 -I/usr/include/aarch64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/aarch64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/aarch64-linux-gnu/7/include-fixed -I/usr/include/aarch64-linux-gnu -I/usr/include /home/swu/projects/xEyes/src/libDsp/ThreadQt.h -o /home/swu/projects/build_xeyes/lib/libDsp/moc_ThreadQt.cpp

/home/swu/projects/build_xeyes/lib/libDsp/moc_DspThread.cpp: /home/swu/projects/xEyes/src/libUtil/util.h \
		/home/swu/projects/xEyes/src/libUtil/DataTypes.h \
		/home/swu/projects/xEyes/src/libUtil/AppEnums.h \
		/home/swu/projects/xEyes/src/libUtil/AppLog.h \
		/home/swu/projects/xEyes/src/libUtil/UtilDefs.h \
		/home/swu/projects/xEyes/src/libUtil/FileUtil.h \
		/home/swu/projects/xEyes/src/libUtil/UtilFuncs.h \
		/home/swu/projects/xEyes/src/libUtil/Roi.h \
		/home/swu/projects/xEyes/src/libUtil/CvUtilFuncs.h \
		/home/swu/projects/xEyes/src/libUtil/CvQtUtil.h \
		/usr/local/Qt-5.9.2/include/QtGui/QImage \
		/usr/local/Qt-5.9.2/include/QtGui/qimage.h \
		/usr/local/Qt-5.9.2/include/QtGui/qtguiglobal.h \
		/usr/local/Qt-5.9.2/include/QtCore/qglobal.h \
		/usr/local/Qt-5.9.2/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/Qt-5.9.2/include/QtCore/qconfig.h \
		/usr/local/Qt-5.9.2/include/QtCore/qtcore-config.h \
		/usr/local/Qt-5.9.2/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.9.2/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.9.2/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.9.2/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.9.2/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.9.2/include/QtCore/qlogging.h \
		/usr/local/Qt-5.9.2/include/QtCore/qflags.h \
		/usr/local/Qt-5.9.2/include/QtCore/qatomic.h \
		/usr/local/Qt-5.9.2/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.9.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.9.2/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.9.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.9.2/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.9.2/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.9.2/include/QtCore/qmutex.h \
		/usr/local/Qt-5.9.2/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.9.2/include/QtCore/qversiontagging.h \
		/usr/local/Qt-5.9.2/include/QtGui/qtgui-config.h \
		/usr/local/Qt-5.9.2/include/QtGui/qcolor.h \
		/usr/local/Qt-5.9.2/include/QtGui/qrgb.h \
		/usr/local/Qt-5.9.2/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.9.2/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.9.2/include/QtCore/qlist.h \
		/usr/local/Qt-5.9.2/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.9.2/include/QtCore/qiterator.h \
		/usr/local/Qt-5.9.2/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.9.2/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.9.2/include/QtCore/qhashfunctions.h \
		/usr/local/Qt-5.9.2/include/QtCore/qchar.h \
		/usr/local/Qt-5.9.2/include/QtCore/qpair.h \
		/usr/local/Qt-5.9.2/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.9.2/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.9.2/include/QtCore/qstring.h \
		/usr/local/Qt-5.9.2/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.9.2/include/QtCore/qregexp.h \
		/usr/local/Qt-5.9.2/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.9.2/include/QtGui/qrgba64.h \
		/usr/local/Qt-5.9.2/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.9.2/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.9.2/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.9.2/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.9.2/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.9.2/include/QtCore/qrect.h \
		/usr/local/Qt-5.9.2/include/QtCore/qmargins.h \
		/usr/local/Qt-5.9.2/include/QtCore/qsize.h \
		/usr/local/Qt-5.9.2/include/QtCore/qpoint.h \
		/usr/local/Qt-5.9.2/include/QtGui/qpixelformat.h \
		/usr/local/Qt-5.9.2/include/QtGui/qtransform.h \
		/usr/local/Qt-5.9.2/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.9.2/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.9.2/include/QtCore/qvector.h \
		/usr/local/Qt-5.9.2/include/QtGui/qregion.h \
		/usr/local/Qt-5.9.2/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.9.2/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.9.2/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.9.2/include/QtCore/qobject.h \
		/usr/local/Qt-5.9.2/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.9.2/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.9.2/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.9.2/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.9.2/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.9.2/include/QtCore/qline.h \
		/usr/local/Qt-5.9.2/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.9.2/include/QtGui/QPixmap \
		/usr/local/Qt-5.9.2/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.9.2/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.9.2/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.9.2/include/QtCore/qhash.h \
		/usr/local/Qt-5.9.2/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.9.2/include/QtCore/QDebug \
		/usr/local/Qt-5.9.2/include/QtCore/qdebug.h \
		/usr/local/Qt-5.9.2/include/QtCore/qmap.h \
		/usr/local/Qt-5.9.2/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.9.2/include/QtCore/qlocale.h \
		/usr/local/Qt-5.9.2/include/QtCore/qvariant.h \
		/usr/local/Qt-5.9.2/include/QtCore/qset.h \
		/usr/local/Qt-5.9.2/include/QtCore/qcontiguouscache.h \
		/home/swu/projects/xEyes/src/libDc/ThreadX.h \
		/home/swu/projects/xEyes/src/libDc/DsDefs.h \
		/home/swu/projects/xEyes/src/libCfg/Cfg.h \
		/home/swu/projects/xEyes/src/libCfg/CfgLog.h \
		/home/swu/projects/xEyes/src/libCfg/CfgBase.h \
		/home/swu/projects/xEyes/src/libCfg/CfgDefs.h \
		/home/swu/projects/xEyes/src/libCfg/CfgCam.h \
		/home/swu/projects/xEyes/src/libCfg/CfgLocalView.h \
		/home/swu/projects/xEyes/src/libDc/DcUI.h \
		/home/swu/projects/xEyes/src/libDc/Dc.h \
		/home/swu/projects/xEyes/src/libDc/YuvCircularQ_h.h \
		/home/swu/projects/xEyes/src/libDc/YuvFrm_h.h \
		/home/swu/projects/xEyes/src/libDc/YuvFrm_d.h \
		/usr/local/cuda/include/cuda_runtime.h \
		/usr/local/cuda/include/crt/host_config.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/crt/host_defines.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/library_types.h \
		/usr/local/cuda/include/channel_descriptor.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/driver_functions.h \
		/usr/local/cuda/include/vector_functions.h \
		/usr/local/cuda/include/vector_functions.hpp \
		/usr/local/cuda/include/crt/device_functions.h \
		/usr/local/cuda/include/crt/device_functions.hpp \
		/usr/local/cuda/include/device_atomic_functions.h \
		/usr/local/cuda/include/device_atomic_functions.hpp \
		/usr/local/cuda/include/crt/device_double_functions.h \
		/usr/local/cuda/include/crt/device_double_functions.hpp \
		/usr/local/cuda/include/sm_20_atomic_functions.h \
		/usr/local/cuda/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda/include/sm_32_atomic_functions.h \
		/usr/local/cuda/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda/include/sm_35_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.hpp \
		/usr/local/cuda/include/sm_20_intrinsics.h \
		/usr/local/cuda/include/sm_20_intrinsics.hpp \
		/usr/local/cuda/include/sm_30_intrinsics.h \
		/usr/local/cuda/include/sm_30_intrinsics.hpp \
		/usr/local/cuda/include/sm_32_intrinsics.h \
		/usr/local/cuda/include/sm_32_intrinsics.hpp \
		/usr/local/cuda/include/sm_35_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.hpp \
		/usr/local/cuda/include/crt/sm_70_rt.h \
		/usr/local/cuda/include/crt/sm_70_rt.hpp \
		/usr/local/cuda/include/surface_functions.h \
		/usr/local/cuda/include/cuda_surface_types.h \
		/usr/local/cuda/include/texture_fetch_functions.h \
		/usr/local/cuda/include/cuda_texture_types.h \
		/usr/local/cuda/include/texture_indirect_functions.h \
		/usr/local/cuda/include/surface_indirect_functions.h \
		/usr/local/cuda/include/crt/common_functions.h \
		/usr/local/cuda/include/crt/math_functions.h \
		/usr/local/cuda/include/crt/func_macro.h \
		/usr/local/cuda/include/crt/math_functions.hpp \
		/usr/local/cuda/include/math_constants.h \
		/usr/local/cuda/include/device_launch_parameters.h \
		/usr/local/cuda/include/npp.h \
		/usr/local/cuda/include/nppversion.h \
		/usr/local/cuda/include/nppdefs.h \
		/usr/local/cuda/include/nppcore.h \
		/usr/local/cuda/include/nppi.h \
		/usr/local/cuda/include/nppi_support_functions.h \
		/usr/local/cuda/include/nppi_data_exchange_and_initialization.h \
		/usr/local/cuda/include/nppi_arithmetic_and_logical_operations.h \
		/usr/local/cuda/include/nppi_color_conversion.h \
		/usr/local/cuda/include/nppi_threshold_and_compare_operations.h \
		/usr/local/cuda/include/nppi_morphological_operations.h \
		/usr/local/cuda/include/nppi_filtering_functions.h \
		/usr/local/cuda/include/nppi_statistics_functions.h \
		/usr/local/cuda/include/nppi_linear_transforms.h \
		/usr/local/cuda/include/nppi_geometry_transforms.h \
		/usr/local/cuda/include/nppi_compression_functions.h \
		/usr/local/cuda/include/nppi_computer_vision.h \
		/usr/local/cuda/include/npps.h \
		/usr/local/cuda/include/npps_support_functions.h \
		/usr/local/cuda/include/npps_initialization.h \
		/usr/local/cuda/include/npps_conversion_functions.h \
		/usr/local/cuda/include/npps_arithmetic_and_logical_operations.h \
		/usr/local/cuda/include/npps_statistics_functions.h \
		/usr/local/cuda/include/npps_filtering_functions.h \
		/home/swu/projects/xEyes/src/libDc/RgbFrm_d.h \
		/home/swu/projects/xEyes/src/libDc/RgbCircularQ_h.h \
		/home/swu/projects/xEyes/src/libDc/RgbFrm_h.h \
		/home/swu/projects/xEyes/src/libDc/FrmInfoCircularQ.h \
		/home/swu/projects/xEyes/src/libDc/FrmInfo.h \
		/home/swu/projects/xEyes/src/libDc/DetFrm_h.h \
		/home/swu/projects/xEyes/src/libDc/DspFrm_h.h \
		/home/swu/projects/xEyes/src/libDsp/ThreadQt.h \
		/usr/local/Qt-5.9.2/include/QtCore/qthread.h \
		/home/swu/projects/xEyes/src/libDsp/DspDefs.h \
		/usr/local/Qt-5.9.2/include/QtCore/QObject \
		/home/swu/projects/xEyes/src/libDsp/DspThread.h \
		/home/swu/projects/build_xeyes/lib/libDsp/moc_predefs.h \
		/usr/local/Qt-5.9.2/bin/moc
	/usr/local/Qt-5.9.2/bin/moc $(DEFINES) --include /home/swu/projects/build_xeyes/lib/libDsp/moc_predefs.h -I/usr/local/Qt-5.9.2/mkspecs/linux-g++ -I/media/swu/ssd512/projects/xEyes/src/makefiles -I/usr/include/c++/7 -I/usr/local/Qt-5.9.2/include -I/usr/local/cuda/include -I/home/swu/projects/xEyes/src -I/home/swu/projects/xEyes/src/libDsp -I/usr/local/Qt-5.9.2/include/QtGui -I/usr/local/Qt-5.9.2/include/QtCore -I/usr/include/c++/7 -I/usr/include/aarch64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/aarch64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/aarch64-linux-gnu/7/include-fixed -I/usr/include/aarch64-linux-gnu -I/usr/include /home/swu/projects/xEyes/src/libDsp/DspThread.h -o /home/swu/projects/build_xeyes/lib/libDsp/moc_DspThread.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

/home/swu/projects/build_xeyes/lib/libDsp/ThreadQt.o: /home/swu/projects/xEyes/src/libDsp/ThreadQt.cpp /home/swu/projects/xEyes/src/libDsp/ThreadQt.h \
		/usr/local/Qt-5.9.2/include/QtCore/qthread.h \
		/usr/local/Qt-5.9.2/include/QtCore/qobject.h \
		/usr/local/Qt-5.9.2/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.9.2/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.9.2/include/QtCore/qglobal.h \
		/usr/local/Qt-5.9.2/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/Qt-5.9.2/include/QtCore/qconfig.h \
		/usr/local/Qt-5.9.2/include/QtCore/qtcore-config.h \
		/usr/local/Qt-5.9.2/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.9.2/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.9.2/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.9.2/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.9.2/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.9.2/include/QtCore/qlogging.h \
		/usr/local/Qt-5.9.2/include/QtCore/qflags.h \
		/usr/local/Qt-5.9.2/include/QtCore/qatomic.h \
		/usr/local/Qt-5.9.2/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.9.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.9.2/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.9.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.9.2/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.9.2/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.9.2/include/QtCore/qmutex.h \
		/usr/local/Qt-5.9.2/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.9.2/include/QtCore/qversiontagging.h \
		/usr/local/Qt-5.9.2/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.9.2/include/QtCore/qstring.h \
		/usr/local/Qt-5.9.2/include/QtCore/qchar.h \
		/usr/local/Qt-5.9.2/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.9.2/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.9.2/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.9.2/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.9.2/include/QtCore/qlist.h \
		/usr/local/Qt-5.9.2/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.9.2/include/QtCore/qiterator.h \
		/usr/local/Qt-5.9.2/include/QtCore/qhashfunctions.h \
		/usr/local/Qt-5.9.2/include/QtCore/qpair.h \
		/usr/local/Qt-5.9.2/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.9.2/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.9.2/include/QtCore/qregexp.h \
		/usr/local/Qt-5.9.2/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.9.2/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.9.2/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.9.2/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.9.2/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.9.2/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.9.2/include/QtCore/qobject_impl.h \
		/home/swu/projects/xEyes/src/libUtil/util.h \
		/home/swu/projects/xEyes/src/libUtil/DataTypes.h \
		/home/swu/projects/xEyes/src/libUtil/AppEnums.h \
		/home/swu/projects/xEyes/src/libUtil/AppLog.h \
		/home/swu/projects/xEyes/src/libUtil/UtilDefs.h \
		/home/swu/projects/xEyes/src/libUtil/FileUtil.h \
		/home/swu/projects/xEyes/src/libUtil/UtilFuncs.h \
		/home/swu/projects/xEyes/src/libUtil/Roi.h \
		/home/swu/projects/xEyes/src/libUtil/CvUtilFuncs.h \
		/home/swu/projects/xEyes/src/libCfg/Cfg.h \
		/home/swu/projects/xEyes/src/libCfg/CfgLog.h \
		/home/swu/projects/xEyes/src/libCfg/CfgBase.h \
		/home/swu/projects/xEyes/src/libCfg/CfgDefs.h \
		/home/swu/projects/xEyes/src/libCfg/CfgCam.h \
		/home/swu/projects/xEyes/src/libCfg/CfgLocalView.h \
		/home/swu/projects/xEyes/src/libDc/DcUI.h \
		/home/swu/projects/xEyes/src/libDc/Dc.h \
		/home/swu/projects/xEyes/src/libDc/YuvCircularQ_h.h \
		/home/swu/projects/xEyes/src/libDc/YuvFrm_h.h \
		/home/swu/projects/xEyes/src/libDc/DsDefs.h \
		/home/swu/projects/xEyes/src/libDc/YuvFrm_d.h \
		/usr/local/cuda/include/cuda_runtime.h \
		/usr/local/cuda/include/crt/host_config.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/crt/host_defines.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/library_types.h \
		/usr/local/cuda/include/channel_descriptor.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/driver_functions.h \
		/usr/local/cuda/include/vector_functions.h \
		/usr/local/cuda/include/vector_functions.hpp \
		/usr/local/cuda/include/crt/device_functions.h \
		/usr/local/cuda/include/crt/device_functions.hpp \
		/usr/local/cuda/include/device_atomic_functions.h \
		/usr/local/cuda/include/device_atomic_functions.hpp \
		/usr/local/cuda/include/crt/device_double_functions.h \
		/usr/local/cuda/include/crt/device_double_functions.hpp \
		/usr/local/cuda/include/sm_20_atomic_functions.h \
		/usr/local/cuda/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda/include/sm_32_atomic_functions.h \
		/usr/local/cuda/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda/include/sm_35_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.hpp \
		/usr/local/cuda/include/sm_20_intrinsics.h \
		/usr/local/cuda/include/sm_20_intrinsics.hpp \
		/usr/local/cuda/include/sm_30_intrinsics.h \
		/usr/local/cuda/include/sm_30_intrinsics.hpp \
		/usr/local/cuda/include/sm_32_intrinsics.h \
		/usr/local/cuda/include/sm_32_intrinsics.hpp \
		/usr/local/cuda/include/sm_35_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.hpp \
		/usr/local/cuda/include/crt/sm_70_rt.h \
		/usr/local/cuda/include/crt/sm_70_rt.hpp \
		/usr/local/cuda/include/surface_functions.h \
		/usr/local/cuda/include/cuda_surface_types.h \
		/usr/local/cuda/include/texture_fetch_functions.h \
		/usr/local/cuda/include/cuda_texture_types.h \
		/usr/local/cuda/include/texture_indirect_functions.h \
		/usr/local/cuda/include/surface_indirect_functions.h \
		/usr/local/cuda/include/crt/common_functions.h \
		/usr/local/cuda/include/crt/math_functions.h \
		/usr/local/cuda/include/crt/func_macro.h \
		/usr/local/cuda/include/crt/math_functions.hpp \
		/usr/local/cuda/include/math_constants.h \
		/usr/local/cuda/include/device_launch_parameters.h \
		/usr/local/cuda/include/npp.h \
		/usr/local/cuda/include/nppversion.h \
		/usr/local/cuda/include/nppdefs.h \
		/usr/local/cuda/include/nppcore.h \
		/usr/local/cuda/include/nppi.h \
		/usr/local/cuda/include/nppi_support_functions.h \
		/usr/local/cuda/include/nppi_data_exchange_and_initialization.h \
		/usr/local/cuda/include/nppi_arithmetic_and_logical_operations.h \
		/usr/local/cuda/include/nppi_color_conversion.h \
		/usr/local/cuda/include/nppi_threshold_and_compare_operations.h \
		/usr/local/cuda/include/nppi_morphological_operations.h \
		/usr/local/cuda/include/nppi_filtering_functions.h \
		/usr/local/cuda/include/nppi_statistics_functions.h \
		/usr/local/cuda/include/nppi_linear_transforms.h \
		/usr/local/cuda/include/nppi_geometry_transforms.h \
		/usr/local/cuda/include/nppi_compression_functions.h \
		/usr/local/cuda/include/nppi_computer_vision.h \
		/usr/local/cuda/include/npps.h \
		/usr/local/cuda/include/npps_support_functions.h \
		/usr/local/cuda/include/npps_initialization.h \
		/usr/local/cuda/include/npps_conversion_functions.h \
		/usr/local/cuda/include/npps_arithmetic_and_logical_operations.h \
		/usr/local/cuda/include/npps_statistics_functions.h \
		/usr/local/cuda/include/npps_filtering_functions.h \
		/home/swu/projects/xEyes/src/libDc/RgbFrm_d.h \
		/home/swu/projects/xEyes/src/libDc/RgbCircularQ_h.h \
		/home/swu/projects/xEyes/src/libDc/RgbFrm_h.h \
		/home/swu/projects/xEyes/src/libDc/FrmInfoCircularQ.h \
		/home/swu/projects/xEyes/src/libDc/FrmInfo.h \
		/home/swu/projects/xEyes/src/libDc/DetFrm_h.h \
		/home/swu/projects/xEyes/src/libDc/DspFrm_h.h \
		/usr/local/Qt-5.9.2/include/QtGui/QPixmap \
		/usr/local/Qt-5.9.2/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.9.2/include/QtGui/qtguiglobal.h \
		/usr/local/Qt-5.9.2/include/QtGui/qtgui-config.h \
		/usr/local/Qt-5.9.2/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.9.2/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.9.2/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.9.2/include/QtCore/qrect.h \
		/usr/local/Qt-5.9.2/include/QtCore/qmargins.h \
		/usr/local/Qt-5.9.2/include/QtCore/qsize.h \
		/usr/local/Qt-5.9.2/include/QtCore/qpoint.h \
		/usr/local/Qt-5.9.2/include/QtGui/qcolor.h \
		/usr/local/Qt-5.9.2/include/QtGui/qrgb.h \
		/usr/local/Qt-5.9.2/include/QtGui/qrgba64.h \
		/usr/local/Qt-5.9.2/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.9.2/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.9.2/include/QtCore/qhash.h \
		/usr/local/Qt-5.9.2/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.9.2/include/QtGui/qimage.h \
		/usr/local/Qt-5.9.2/include/QtGui/qpixelformat.h \
		/usr/local/Qt-5.9.2/include/QtGui/qtransform.h \
		/usr/local/Qt-5.9.2/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.9.2/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.9.2/include/QtCore/qvector.h \
		/usr/local/Qt-5.9.2/include/QtGui/qregion.h \
		/usr/local/Qt-5.9.2/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.9.2/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.9.2/include/QtCore/qline.h \
		/usr/local/Qt-5.9.2/include/QtGui/qpainterpath.h \
		/home/swu/projects/xEyes/src/libDsp/DspDefs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /home/swu/projects/build_xeyes/lib/libDsp/ThreadQt.o /home/swu/projects/xEyes/src/libDsp/ThreadQt.cpp

/home/swu/projects/build_xeyes/lib/libDsp/DspThread.o: /home/swu/projects/xEyes/src/libDsp/DspThread.cpp /home/swu/projects/xEyes/src/libDsp/DspThread.h \
		/home/swu/projects/xEyes/src/libUtil/util.h \
		/home/swu/projects/xEyes/src/libUtil/DataTypes.h \
		/home/swu/projects/xEyes/src/libUtil/AppEnums.h \
		/home/swu/projects/xEyes/src/libUtil/AppLog.h \
		/home/swu/projects/xEyes/src/libUtil/UtilDefs.h \
		/home/swu/projects/xEyes/src/libUtil/FileUtil.h \
		/home/swu/projects/xEyes/src/libUtil/UtilFuncs.h \
		/home/swu/projects/xEyes/src/libUtil/Roi.h \
		/home/swu/projects/xEyes/src/libUtil/CvUtilFuncs.h \
		/home/swu/projects/xEyes/src/libUtil/CvQtUtil.h \
		/usr/local/Qt-5.9.2/include/QtGui/QImage \
		/usr/local/Qt-5.9.2/include/QtGui/qimage.h \
		/usr/local/Qt-5.9.2/include/QtGui/qtguiglobal.h \
		/usr/local/Qt-5.9.2/include/QtCore/qglobal.h \
		/usr/local/Qt-5.9.2/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/Qt-5.9.2/include/QtCore/qconfig.h \
		/usr/local/Qt-5.9.2/include/QtCore/qtcore-config.h \
		/usr/local/Qt-5.9.2/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.9.2/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.9.2/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.9.2/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.9.2/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.9.2/include/QtCore/qlogging.h \
		/usr/local/Qt-5.9.2/include/QtCore/qflags.h \
		/usr/local/Qt-5.9.2/include/QtCore/qatomic.h \
		/usr/local/Qt-5.9.2/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.9.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.9.2/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.9.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.9.2/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.9.2/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.9.2/include/QtCore/qmutex.h \
		/usr/local/Qt-5.9.2/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.9.2/include/QtCore/qversiontagging.h \
		/usr/local/Qt-5.9.2/include/QtGui/qtgui-config.h \
		/usr/local/Qt-5.9.2/include/QtGui/qcolor.h \
		/usr/local/Qt-5.9.2/include/QtGui/qrgb.h \
		/usr/local/Qt-5.9.2/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.9.2/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.9.2/include/QtCore/qlist.h \
		/usr/local/Qt-5.9.2/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.9.2/include/QtCore/qiterator.h \
		/usr/local/Qt-5.9.2/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.9.2/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.9.2/include/QtCore/qhashfunctions.h \
		/usr/local/Qt-5.9.2/include/QtCore/qchar.h \
		/usr/local/Qt-5.9.2/include/QtCore/qpair.h \
		/usr/local/Qt-5.9.2/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.9.2/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.9.2/include/QtCore/qstring.h \
		/usr/local/Qt-5.9.2/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.9.2/include/QtCore/qregexp.h \
		/usr/local/Qt-5.9.2/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.9.2/include/QtGui/qrgba64.h \
		/usr/local/Qt-5.9.2/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.9.2/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.9.2/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.9.2/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.9.2/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.9.2/include/QtCore/qrect.h \
		/usr/local/Qt-5.9.2/include/QtCore/qmargins.h \
		/usr/local/Qt-5.9.2/include/QtCore/qsize.h \
		/usr/local/Qt-5.9.2/include/QtCore/qpoint.h \
		/usr/local/Qt-5.9.2/include/QtGui/qpixelformat.h \
		/usr/local/Qt-5.9.2/include/QtGui/qtransform.h \
		/usr/local/Qt-5.9.2/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.9.2/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.9.2/include/QtCore/qvector.h \
		/usr/local/Qt-5.9.2/include/QtGui/qregion.h \
		/usr/local/Qt-5.9.2/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.9.2/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.9.2/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.9.2/include/QtCore/qobject.h \
		/usr/local/Qt-5.9.2/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.9.2/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.9.2/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.9.2/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.9.2/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.9.2/include/QtCore/qline.h \
		/usr/local/Qt-5.9.2/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.9.2/include/QtGui/QPixmap \
		/usr/local/Qt-5.9.2/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.9.2/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.9.2/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.9.2/include/QtCore/qhash.h \
		/usr/local/Qt-5.9.2/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.9.2/include/QtCore/QDebug \
		/usr/local/Qt-5.9.2/include/QtCore/qdebug.h \
		/usr/local/Qt-5.9.2/include/QtCore/qmap.h \
		/usr/local/Qt-5.9.2/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.9.2/include/QtCore/qlocale.h \
		/usr/local/Qt-5.9.2/include/QtCore/qvariant.h \
		/usr/local/Qt-5.9.2/include/QtCore/qset.h \
		/usr/local/Qt-5.9.2/include/QtCore/qcontiguouscache.h \
		/home/swu/projects/xEyes/src/libDc/ThreadX.h \
		/home/swu/projects/xEyes/src/libDc/DsDefs.h \
		/home/swu/projects/xEyes/src/libCfg/Cfg.h \
		/home/swu/projects/xEyes/src/libCfg/CfgLog.h \
		/home/swu/projects/xEyes/src/libCfg/CfgBase.h \
		/home/swu/projects/xEyes/src/libCfg/CfgDefs.h \
		/home/swu/projects/xEyes/src/libCfg/CfgCam.h \
		/home/swu/projects/xEyes/src/libCfg/CfgLocalView.h \
		/home/swu/projects/xEyes/src/libDc/DcUI.h \
		/home/swu/projects/xEyes/src/libDc/Dc.h \
		/home/swu/projects/xEyes/src/libDc/YuvCircularQ_h.h \
		/home/swu/projects/xEyes/src/libDc/YuvFrm_h.h \
		/home/swu/projects/xEyes/src/libDc/YuvFrm_d.h \
		/usr/local/cuda/include/cuda_runtime.h \
		/usr/local/cuda/include/crt/host_config.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/crt/host_defines.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/library_types.h \
		/usr/local/cuda/include/channel_descriptor.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/driver_functions.h \
		/usr/local/cuda/include/vector_functions.h \
		/usr/local/cuda/include/vector_functions.hpp \
		/usr/local/cuda/include/crt/device_functions.h \
		/usr/local/cuda/include/crt/device_functions.hpp \
		/usr/local/cuda/include/device_atomic_functions.h \
		/usr/local/cuda/include/device_atomic_functions.hpp \
		/usr/local/cuda/include/crt/device_double_functions.h \
		/usr/local/cuda/include/crt/device_double_functions.hpp \
		/usr/local/cuda/include/sm_20_atomic_functions.h \
		/usr/local/cuda/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda/include/sm_32_atomic_functions.h \
		/usr/local/cuda/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda/include/sm_35_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.hpp \
		/usr/local/cuda/include/sm_20_intrinsics.h \
		/usr/local/cuda/include/sm_20_intrinsics.hpp \
		/usr/local/cuda/include/sm_30_intrinsics.h \
		/usr/local/cuda/include/sm_30_intrinsics.hpp \
		/usr/local/cuda/include/sm_32_intrinsics.h \
		/usr/local/cuda/include/sm_32_intrinsics.hpp \
		/usr/local/cuda/include/sm_35_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.hpp \
		/usr/local/cuda/include/crt/sm_70_rt.h \
		/usr/local/cuda/include/crt/sm_70_rt.hpp \
		/usr/local/cuda/include/surface_functions.h \
		/usr/local/cuda/include/cuda_surface_types.h \
		/usr/local/cuda/include/texture_fetch_functions.h \
		/usr/local/cuda/include/cuda_texture_types.h \
		/usr/local/cuda/include/texture_indirect_functions.h \
		/usr/local/cuda/include/surface_indirect_functions.h \
		/usr/local/cuda/include/crt/common_functions.h \
		/usr/local/cuda/include/crt/math_functions.h \
		/usr/local/cuda/include/crt/func_macro.h \
		/usr/local/cuda/include/crt/math_functions.hpp \
		/usr/local/cuda/include/math_constants.h \
		/usr/local/cuda/include/device_launch_parameters.h \
		/usr/local/cuda/include/npp.h \
		/usr/local/cuda/include/nppversion.h \
		/usr/local/cuda/include/nppdefs.h \
		/usr/local/cuda/include/nppcore.h \
		/usr/local/cuda/include/nppi.h \
		/usr/local/cuda/include/nppi_support_functions.h \
		/usr/local/cuda/include/nppi_data_exchange_and_initialization.h \
		/usr/local/cuda/include/nppi_arithmetic_and_logical_operations.h \
		/usr/local/cuda/include/nppi_color_conversion.h \
		/usr/local/cuda/include/nppi_threshold_and_compare_operations.h \
		/usr/local/cuda/include/nppi_morphological_operations.h \
		/usr/local/cuda/include/nppi_filtering_functions.h \
		/usr/local/cuda/include/nppi_statistics_functions.h \
		/usr/local/cuda/include/nppi_linear_transforms.h \
		/usr/local/cuda/include/nppi_geometry_transforms.h \
		/usr/local/cuda/include/nppi_compression_functions.h \
		/usr/local/cuda/include/nppi_computer_vision.h \
		/usr/local/cuda/include/npps.h \
		/usr/local/cuda/include/npps_support_functions.h \
		/usr/local/cuda/include/npps_initialization.h \
		/usr/local/cuda/include/npps_conversion_functions.h \
		/usr/local/cuda/include/npps_arithmetic_and_logical_operations.h \
		/usr/local/cuda/include/npps_statistics_functions.h \
		/usr/local/cuda/include/npps_filtering_functions.h \
		/home/swu/projects/xEyes/src/libDc/RgbFrm_d.h \
		/home/swu/projects/xEyes/src/libDc/RgbCircularQ_h.h \
		/home/swu/projects/xEyes/src/libDc/RgbFrm_h.h \
		/home/swu/projects/xEyes/src/libDc/FrmInfoCircularQ.h \
		/home/swu/projects/xEyes/src/libDc/FrmInfo.h \
		/home/swu/projects/xEyes/src/libDc/DetFrm_h.h \
		/home/swu/projects/xEyes/src/libDc/DspFrm_h.h \
		/home/swu/projects/xEyes/src/libDsp/ThreadQt.h \
		/usr/local/Qt-5.9.2/include/QtCore/qthread.h \
		/home/swu/projects/xEyes/src/libDsp/DspDefs.h \
		/usr/local/Qt-5.9.2/include/QtCore/QObject
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /home/swu/projects/build_xeyes/lib/libDsp/DspThread.o /home/swu/projects/xEyes/src/libDsp/DspThread.cpp

/home/swu/projects/build_xeyes/lib/libDsp/moc_ThreadQt.o: /home/swu/projects/build_xeyes/lib/libDsp/moc_ThreadQt.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /home/swu/projects/build_xeyes/lib/libDsp/moc_ThreadQt.o /home/swu/projects/build_xeyes/lib/libDsp/moc_ThreadQt.cpp

/home/swu/projects/build_xeyes/lib/libDsp/moc_DspThread.o: /home/swu/projects/build_xeyes/lib/libDsp/moc_DspThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /home/swu/projects/build_xeyes/lib/libDsp/moc_DspThread.o /home/swu/projects/build_xeyes/lib/libDsp/moc_DspThread.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

